name: time_manage
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  build_runner: ^2.4.11
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_pin_code_fields: ^2.2.0
  fluttertoast: ^8.2.6
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  pin_code_fields: ^8.0.1
  shared_preferences: ^2.2.3
  talker: ^4.3.2
  talker_flutter: ^4.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android:
    generate: true
    image_path: "lib/assets/image.png"
  image_path: "lib/assets/image.png"
  min_sdk_android: 21 
  web:
    generate: true
    image_path: "lib/assets/image.png"

flutter:
  uses-material-design: true
